/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LeagueDto } from '../../models/league-dto';

export interface LeagueControllerFindAll$Params {
}

export function leagueControllerFindAll(http: HttpClient, rootUrl: string, params?: LeagueControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeagueDto>>> {
  const rb = new RequestBuilder(rootUrl, leagueControllerFindAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LeagueDto>>;
    })
  );
}

leagueControllerFindAll.PATH = '/api/league';
