/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CategoryDto {
  icon: string;
  id: string;
  name?: string;
  order: number;
  section: number;
}
