/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { categoryControllerFindAll } from '../fn/category/category-controller-find-all';
import { CategoryControllerFindAll$Params } from '../fn/category/category-controller-find-all';
import { CategoryDto } from '../models/category-dto';

@Injectable({ providedIn: 'root' })
export class CategoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `categoryControllerFindAll()` */
  static readonly CategoryControllerFindAllPath = '/api/category';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `categoryControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoryControllerFindAll$Response(params?: CategoryControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CategoryDto>>> {
    return categoryControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `categoryControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  categoryControllerFindAll(params?: CategoryControllerFindAll$Params, context?: HttpContext): Observable<Array<CategoryDto>> {
    return this.categoryControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CategoryDto>>): Array<CategoryDto> => r.body)
    );
  }

}
