/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { leagueControllerFindAll } from '../fn/league/league-controller-find-all';
import { LeagueControllerFindAll$Params } from '../fn/league/league-controller-find-all';
import { LeagueDto } from '../models/league-dto';

@Injectable({ providedIn: 'root' })
export class LeagueService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `leagueControllerFindAll()` */
  static readonly LeagueControllerFindAllPath = '/api/league';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `leagueControllerFindAll()` instead.
   *
   * This method doesn't expect any request body.
   */
  leagueControllerFindAll$Response(params?: LeagueControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LeagueDto>>> {
    return leagueControllerFindAll(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `leagueControllerFindAll$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  leagueControllerFindAll(params?: LeagueControllerFindAll$Params, context?: HttpContext): Observable<Array<LeagueDto>> {
    return this.leagueControllerFindAll$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<LeagueDto>>): Array<LeagueDto> => r.body)
    );
  }

}
