/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { BaseService } from './base-service';
export { RequestBuilder } from './request-builder';
export { ApiModule } from './api.module';
export type { StrictHttpResponse } from './strict-http-response';
export type { CategoryDto } from './models/category-dto';
export type { LeagueDto } from './models/league-dto';
export { CategoryService } from './services/category.service';
export { LeagueService } from './services/league.service';
