/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryDto } from './models/category-dto';
export type { LeagueDto } from './models/league-dto';
