/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { CategoryService } from './services/category.service';
export { LeagueService } from './services/league.service';
